# Change these first
owner: pusimgit # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: SIAKAD
    url: https://siakad.unmer.ac.id/
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: PMB
    url: https://pmb.unmer.ac.id/
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: SDM
    url: https://sdm.unmer.ac.id/
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: Payment Gateway
    url: https://payment.unmer.ac.id/
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: API
    url: https://api.unmer.ac.id/
    expectedStatusCodes:
      - 200
      - 201
      - 404
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: BP3M
    url: https://bp3m.unmer.ac.id/
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: SISTER
    url: https://sister.unmer.ac.id/
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: eClass
    url: https://eclass.unmer.ac.id/
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: Website Unmer
    url: https://unmer.ac.id/
    maxResponseTime: 10000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: Development
    url: https://dev.unmer.ac.id/siakad/
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: Eprints
    url: https://eprints.unmer.ac.id
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: Jurnal
    url: https://jurnal.unmer.ac.id
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: Network CBN
    check: "tcp-ping"
    url: $CBN_SITE
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: Network IFORTE
    check: "tcp-ping"
    url: $IFORTE_SITE
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: Network NUSA
    check: "tcp-ping"
    url: $NUSA_SITE
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.ico
  - name: Google DNS 1
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53
    icon: https://www.google.com/favicon.ico


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  name: Status
  cname: status.unmer.ac.id
  logoUrl: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/logo.png
  favicon: https://raw.githubusercontent.com/pusimgit/upptime/master/assets/favicon.png
  robotsText: "User-agent: * \n Disallow: /"
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Home
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
